name: huart
description: Hue api with dart language
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

workspace:
  # - apps/flutter_poker

dev_dependencies:
  custom_lint: ^0.7.5
  melos: ^7.1.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

melos:
  name: huart
  sdkPath: .fvm/flutter_sdk

  scripts:
    analyze:
      run: |
        set -o pipefail && fvm flutter pub global run melos exec -- "fvm flutter analyze --fatal-infos . && find . \
          -type f \
          -name '*.dart' \
          -not -path '*/bricks/*' \
          -not -path '*/*build/*' \
          -not -path '*/.dart_tool/*' \
          -not -path '*/gen/*' \
          -not -name '*.config.dart' \
          -not -name '*.freezed.dart' \
          -not -name '*.g.dart' \
          -not -name '*.gen.dart' \
          -not -name '*.mocks.dart' \
          -not -name 'pigeon.dart' \
          -not -name '*.tailor.dart' \
          -not -name '*.givn.dart' \
          -not -name 'app_localizations*' | xargs fvm dart format --output none --set-exit-if-changed" \
          | grep -E -i 'No issues found|exit code|Changed \.\/|info •' &&
        fvm flutter pub global run melos exec -c 4 --depends-on="custom_lint" "fvm dart run custom_lint"
      description: |
        Run `flutter analyze` and checks formatting of dart files in all packages.
         - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  command:
      bootstrap:
        enforceLockfile: true
        runPubGetInParallel: true
        environment:
        sdk: '>=3.8.0 <4.0.0'
        flutter: '>=3.27.0'
      dependencies:
      dev_dependencies:
        build_runner: ^2.4.15
        custom_lint: ^0.7.5
        very_good_analysis: ^6.0.0