name: hue_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2
resolution: workspace

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  retrofit: ^4.8.0
  talker_dio_logger: ^5.0.2
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  retrofit_generator: ^10.1.1
  test: ^1.25.6
